[env]
CARGO_TERM_COLOR = "always"

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.build-release]
command = "cargo"
args = ["build", "--release"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--all-targets", "--", "-D", "warnings"]

[tasks.fmt]
command = "cargo"
args = ["fmt", "--all"]

[tasks.fmt-check]
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.check]
command = "cargo"
args = ["check", "--all-targets"]

[tasks.coverage]
command = "cargo"
args = ["tarpaulin", "--all"]

[tasks.fuzz]
command = "cargo"
args = ["fuzz", "run"]

[tasks.ci]
dependencies = ["fmt-check", "clippy", "test"]
