[package]
name = "cmdcode"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "cmdcode"
path = "src/main.rs"

[dependencies]
cmdcode-core.workspace = true
cmdcode-server.workspace = true
clap.workspace = true
dirs = "5"
reqwest = { version = "0.12", features = ["json"] }
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
